# coding: utf8
# minqlx - A Quake Live server administrator bot.
# Copyright (C) 2015 Mino <mino@minomino.org>

# This file is part of minqlx.

# minqlx is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# minqlx is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with minqlx. If not, see <http://www.gnu.org/licenses/>.

import minqlx
import random
import time
import re

from minqlx.database import Redis
_re_ = {}
_izi_ = {}
_izi_multi_ = {}


def add_sound(key, regex, path):
    _re_[key] = [re.compile(regex, flags=re.IGNORECASE), path]


def add_izi_sound(key, regex, path):
    _izi_[key] = [re.compile(regex, flags=re.IGNORECASE), path]


def add_izi_multi_sound(key, regex, path, rand):
    _izi_multi_[key] = [re.compile(regex, flags=re.IGNORECASE), path, rand]


add_sound("hahaha yeah", r"^haha(?:ha)?,? yeah?\W?$", "sound/player/lucy/taunt.wav") # not works
add_sound("haha yeah haha", r"^haha(?:ha)?,? yeah?,? haha\W?$", "sound/player/biker/taunt.wav")
add_sound("yeah hahaha", r"^yeah?,? haha(?:ha)\W?$", "sound/player/razor/taunt.wav")
add_sound("duahaha", r"^duahaha(?:ha)?\W?$", "sound/player/keel/taunt.wav")
add_sound("hahaha", r"^hahaha\W?$", "sound/player/santa/taunt.wav")
add_sound("glhf", r"^(?:gl ?hf\W?)|(?:hf\W?)|(?:gl hf\W?)", "sound/vo/crash_new/39_01.wav")
add_sound("f3", r"^(?:(?:press )?f3)|ready(?: up)?\W?", "sound/vo/crash_new/36_04.wav")
add_sound("welcome", r"^welcome to (?:ql|quake live)\W?$", "sound/vo_evil/welcome")
add_sound("go", r"^go\W?$", "sound/vo/go")
add_sound("you win", r"^you win\W?$", "sound/vo_female/you_win.wav")
add_sound("you lose", r"^you lose\W?$", "sound/vo/you_lose.wav")
add_sound("beep boop", r"^beep boop\W?$", "sound/player/tankjr/taunt.wav")
add_sound("denied", r"^denied\W?$", "sound/vo/denied")
add_sound("balls out", r"^ball'?s out\W?$", "sound/vo_female/balls_out")
add_sound("one", r"^one\W?$", "sound/vo_female/one")
add_sound("two", r"^two\W?$", "sound/vo_female/two")
add_sound("three", r"^three\W?$", "sound/vo_female/three")
add_sound("fight", r"^fight\W?$", "sound/vo_evil/fight")
add_sound("gauntlet", r"^gauntlet\W?$", "sound/vo_evil/gauntlet")
add_sound("humiliation", r"^humiliation\W?$", "sound/vo_evil/humiliation1")
add_sound("perfect", r"^perfect\W?$", "sound/vo_evil/perfect")
add_sound("wah wah wah wah", r"^wa+h wa+h wa+h wa+h\W?$", "sound/misc/yousuck")
add_sound("ah ah ah", r"^a+h a+h a+h\W?$", "sound/player/slash/taunt.wav")
add_sound("oink", r"^oink\W?$", "sound/player/sorlag/pain50_1.wav")
add_sound("argh", r"^a+rgh\W?$", "sound/player/doom/taunt.wav")
add_sound("hah haha", r"^hah haha\W?$", "sound/player/hunter/taunt.wav")
add_sound("woohoo", r"^woo+hoo+\W?$", "sound/player/janet/taunt.wav")
add_sound("quakelive | ql", r"^(?:ql|quake live)\W?$", "sound/vo_female/quake_live")
add_sound("$ | € | £", "(?:\$|€|£)\d+", "sound/misc/chaching")
add_sound("uh ah", r"^uh ah$", "sound/player/mynx/taunt.wav")
add_sound("oohwee", r"^ooh+wee\W?$", "sound/player/anarki/taunt.wav")
add_sound("erah", r"^erah\W?$", "sound/player/bitterman/taunt.wav")
add_sound("yeahhh", r"^yeahhh\W?$", "sound/player/major/taunt.wav")
add_sound("scream", r"^scream\W?$", "sound/player/bones/taunt.wav")
add_sound("salute", r"^salute\W?$", "sound/player/sarge/taunt.wav")
add_sound("squish", r"^squish\W?$", "sound/player/orb/taunt.wav")
add_sound("oh god", r"^oh god\W?$", "sound/player/ranger/taunt.wav")
add_sound("snarl", r"^snarl\W?$", "sound/player/sorlag/taunt.wav")
add_sound("007", r"^007\W?$", "sound/funnysounds/007.wav")
add_sound("adamsfamily", r"^adamsfamily\W?$", "sound/funnysounds/adamsfamily.ogg")
add_sound("allahuakbar", r"^allahuakbar\W?$", "sound/funnysounds/allahuakbar.ogg")
add_sound("allstar", r"^allstar\W?$", "sound/funnysounds/allstar.ogg")
add_sound("asskicking", r"^asskicking\W?$", "sound/funnysounds/asskicking.ogg")
add_sound("baby baby", r"^baby baby\W?$", "sound/funnysounds/babybaby.ogg")
add_sound("babylaughing", r"^babylaughing\W?$", "sound/funnysounds/babylaughing.ogg")
add_sound("Ill be back", r"^I'?ll be back\W?$", "sound/funnysounds/beback.ogg")
add_sound("benny hill", r"^benny hill\W?$", "sound/funnysounds/bennyhill.ogg")
add_sound("boom headshot", r"^boom headshot\W?$", "sound/funnysounds/boomheadshot.ogg")
add_sound("brightsideoflife", r"^brightsideoflife\W?$", "sound/funnysounds/brightsideoflife.ogg")
add_sound("bullshitter", r"^bullshitter\W?$", "sound/funnysounds/bullshitter.ogg")
add_sound("cant touch this", r"^can'?t touch this\W?$", "sound/funnysounds/canttouchthis.ogg")
add_sound("champions", r"^champions\W?$", "sound/funnysounds/champions.ogg")
add_sound("cowards", r"^cowards\W?$", "sound/funnysounds/cowards.ogg")
add_sound("damnit", r"^damnit\W?$", "sound/funnysounds/damnit.ogg")
add_sound("deadsoon", r"^deadsoon\W?$", "sound/funnysounds/deadsoon.ogg")
add_sound("defeated", r"^defeated\W?$", "sound/funnysounds/defeated.ogg")
add_sound("freestyler", r"^freestyler\W?$", "sound/funnysounds/freestyler.ogg")
add_sound("fuckfuck", r"^fuckfuck\W?$", "sound/funnysounds/fuckfuck.ogg")
add_sound("fucking kids", r"^fucking kids\W?$", "sound/funnysounds/fuckingkids.ogg")
add_sound("gangnam", r"^gangnam\W?$", "sound/funnysounds/gangnam.ogg")
add_sound("get out the way", r"^get out the way\W?$", "sound/funnysounds/getouttheway.ogg")
add_sound("girl look", r"^girl look\W?$", "sound/funnysounds/girllook.ogg")
add_sound("gnr guitar", r"^gnr guitar\W?$", "sound/funnysounds/gnrguitar.ogg")
add_sound("goddamn right", r"^goddamn right\W?$", "sound/funnysounds/goddamnright.ogg")
add_sound("gotcha", r"^gotcha\W?$", "sound/funnysounds/gotcha.ogg")
add_sound("hakunamatata", r"^hakunamatata\W?$", "sound/funnysounds/hakunamatata.ogg")
add_sound("hello", r"^hello\W?$", "sound/funnysounds/hello.ogg")
add_sound("how are you", r"^how are you\W?$", "sound/funnysounds/howareyou.ogg")
add_sound("ibet", r"^ibet\W?$", "sound/funnysounds/ibet.ogg")
add_sound("imsexy", r"^imsexy\W?$", "sound/funnysounds/imsexy.ogg")
add_sound("incoming", r"^incoming\W?$", "sound/funnysounds/incoming.ogg")
add_sound("i see assholes", r"^i see assholes\W?$", "sound/funnysounds/iseeassholes.ogg")
add_sound("jump motherfucker", r"^jump motherfucker\W?$", "sound/funnysounds/jackpot.ogg")
add_sound("just do it", r"^just do it\W?$", "sound/funnysounds/jumpmotherfucker.ogg")
add_sound("jackpot", r"^jackpot\W?$", "sound/funnysounds/justdoit.ogg")
add_sound("keep on fighting", r"^keep on fighting\W?$", "sound/funnysounds/keeponfighting.ogg")
add_sound("lion king", r"^lion king\W?$", "sound/funnysounds/lionking.ogg")
add_sound("losing my religion", r"^losing my religion\W?$", "sound/funnysounds/losingmyreligion.ogg")
add_sound("mahnamahna", r"^mahnamahna\W?$", "sound/funnysounds/mahnamahna.ogg")
add_sound("mario", r"^mario\W?$", "sound/funnysounds/mario.ogg")
add_sound("mimimi", r"^mimimi\W?$", "sound/funnysounds/mimimi.ogg")
add_sound("moan", r"^moan\W?$", "sound/funnysounds/moan.ogg")
add_sound("my name", r"^my name\W?$", "sound/funnysounds/myname.ogg")
add_sound("no time for loosers", r"^no time for loosers\W?$", "sound/funnysounds/notimeforloosers.ogg")
add_sound("rocky", r"^rocky\W?$", "sound/funnysounds/rocky")
add_sound("samba", r"^samba\W?$", "sound/funnysounds/samba.ogg")
add_sound("scatman", r"^scatman\W?$", "sound/funnysounds/silence.ogg")
add_sound("silence", r"^silence\W?$", "sound/funnysounds/scatman.ogg")
add_sound("surprise", r"^surprise\W?$", "sound/funnysounds/stayinalive.ogg")
add_sound("teamwork", r"^teamwork\W?$", "sound/funnysounds/surprise.ogg")
add_sound("stayin alive", r"^stayin alive\W?$", "sound/funnysounds/teamwork.ogg")
add_sound("this is sparta", r"^this is sparta\W?$", "sound/funnysounds/thisissparta.ogg")
add_sound("tututu", r"^tututu\W?$", "sound/funnysounds/tuturu.ogg")
add_sound("tuturu", r"^tututu\W?$", "sound/funnysounds/tuturu.ogg")
add_sound("what is love", r"^what is love\W?$", "sound/funnysounds/whatislove.ogg")
add_sound("why mad", r"^why mad\W?$", "sound/funnysounds/whymad.ogg")
add_sound("yhehehe", r"^yhehehe\W?$", "sound/funnysounds/yhehehe.ogg")
add_sound("ymca", r"^ymca\W?$", "sound/funnysounds/ymca.ogg")
add_sound("you fucked mywife", r"^you fucked mywife\W?$", "sound/funnysounds/youfuckedmywife.ogg")
add_sound("all the things", r"^all the things\W?$", "sound/funnysounds/allthethings.ogg")
add_sound("amazing", r"^amazing\W?$", "sound/funnysounds/amazing.ogg")
add_sound("ameno", r"^ameno\W?$", "sound/funnysounds/ameno.ogg")
add_sound("america", r"^america\W?$", "sound/funnysounds/america.ogg")
add_sound("amerika", r"^amerika\W?$", "sound/funnysounds/amerika.ogg")
add_sound("and nothing else", r"^and nothing else\W?$", "sound/funnysounds/andnothingelse.ogg")
add_sound("animals", r"^animals\W?$", "sound/funnysounds/animals.ogg")
add_sound("just a scratch", r"^just a scratch\W?$", "sound/funnysounds/ascratch.ogg")
add_sound("ave", r"^ave\W?$", "sound/funnysounds/ave.ogg")
add_sound("baby baby", r"^baby baby\W?$", "sound/funnysounds/babybaby.ogg")
add_sound("baby evil", r"^baby evil\W?$", "sound/funnysounds/babyevillaugh.ogg")
add_sound("benzin", r"^benzin\W?$", "sound/funnysounds/benzin.ogg")
add_sound("blue wins", r"^blue wins\W?$", "sound/funnysounds/bluewins.ogg")
add_sound("bonkers", r"^bonkers\W?$", "sound/funnysounds/bonkers.ogg")
add_sound("booo", r"^booo\W?$", "sound/funnysounds/booo.ogg")
add_sound("boring", r"^boring\W?$", "sound/funnysounds/boring.ogg")
add_sound("boze", r"^boze\W?$", "sound/funnysounds/boze.ogg")
add_sound("buckdich", r"^buckdich\W?$", "sound/funnysounds/buckdich.ogg")
add_sound("burns burns", r"^burns burns\W?$", "sound/funnysounds/burnsburns.ogg")
add_sound("camel toe", r"^camel toe\W?$", "sound/funnysounds/cameltoe.ogg")
add_sound("cccp", r"^cccp\W?$", "sound/funnysounds/cccp.ogg")
add_sound("chicken", r"^chicken\W?$", "sound/funnysounds/chicken.ogg")
add_sound("chocolate rain", r"^chocolate rain\W?$", "sound/funnysounds/chocolaterain.ogg")
add_sound("coin", r"^coin\W?$", "sound/funnysounds/coin.ogg")
add_sound("come", r"^come\W?$", "sound/funnysounds/come.ogg")
add_sound("countdown", r"^countdown\W?$", "sound/funnysounds/countdown.ogg")
add_sound("crazy", r"^crazy\W?$", "sound/funnysounds/crazy.ogg")
add_sound("you are a cunt", r"^you are a cunt\W?$", "sound/funnysounds/cunt.ogg")
add_sound("devil", r"^devil\W?$", "sound/funnysounds/devil.ogg")
add_sound("doesnt love you", r"^doesn'?t love you\W?$", "sound/funnysounds/doesntloveyou.ogg")
add_sound("du hast", r"^du hast\W?$", "sound/funnysounds/duhast.ogg")
add_sound("du bist", r"^du bist\W?$", "sound/funnysounds/dubist.ogg")
add_sound("dumb ways", r"^dumb ways\W?$", "sound/funnysounds/dumbways.ogg")    # works	elif _re_['dumbways'].match(msg).play_sound("sound/funnysounds/dumbways.ogg")
add_sound("education", r"^education\W?$", "sound/funnysounds/education.ogg")   # does NOT work	elif _re_['education'].match(msg).play_sound("sound/funnysounds/education.ogg")
add_sound("einschrei", r"^einschrei\W?$", "sound/funnysounds/einschrei.ogg")
add_sound("electro", r"^electro\W?$", "sound/funnysounds/electro.ogg")
add_sound("elementary", r"^elementary\W?$", "sound/funnysounds/elementary.ogg")
add_sound("engel", r"^engel\W?$", "sound/funnysounds/engel.ogg")
add_sound("erstwenn", r"^erstwenn\W?$", "sound/funnysounds/erstwenn.ogg")
add_sound("exitlight", r"^exitlight\W?$", "sound/funnysounds/exitlight.ogg")
add_sound("faint", r"^faint\W?$", "sound/funnysounds/faint.ogg")
add_sound("fatality", r"^fatality\W?$", "sound/funnysounds/fatality.ogg")
add_sound("flesh wound", r"^flesh wound\W?$", "sound/funnysounds/fleshwound.ogg")
add_sound("for you", r"^for you\W?$", "sound/funnysounds/foryou.ogg")
add_sound("fucking burger", r"^fucking burger\W?$", "sound/funnysounds/fuckingburger.ogg")
add_sound("ganjaman", r"^ganjaman\W?$", "sound/funnysounds/ganjaman.ogg")
add_sound("gay", r"^gay\W?$", "sound/funnysounds/gay.ogg")
add_sound("get crowbar", r"^get crowbar\W?$", "sound/funnysounds/getcrowbar.ogg")
add_sound("ghostbusters", r"^ghostbusters\W?$", "sound/funnysounds/ghostbusters.ogg")
add_sound("girly", r"^girly\W?$", "sound/funnysounds/girly.ogg")
add_sound("goodby eandrea", r"^goodbye andrea\W?$", "sound/funnysounds/goodbyeandrea.ogg")
add_sound("goodbye sarah", r"^goodbye sarah\W?$", "sound/funnysounds/goodbyesarah.ogg")
add_sound("hammertime", r"^hammertime\W?$", "sound/funnysounds/hammertime.ogg")
add_sound("hellstestern", r"^hellstestern\W?$", "sound/funnysounds/hellstestern.ogg")
add_sound("holy", r"^holy\W?$", "sound/funnysounds/holy.ogg")
add_sound("hoppereiter", r"^hoppereiter\W?$", "sound/funnysounds/hoppereiter.ogg")
add_sound("hush", r"^hush\W?$", "sound/funnysounds/hush.ogg")
add_sound("i cant believe", r"^i can'?t believe\W?$", "sound/funnysounds/icantbelieve.ogg")
add_sound("ichtuedieweh", r"^ichtuedieweh\W?$", "sound/funnysounds/ichtuedieweh.ogg")
add_sound("i do parkour", r"^i do parkour\W?$", "sound/funnysounds/idoparkour.ogg")
add_sound("i hate all", r"^i hate all\W?$", "sound/funnysounds/ihateall.ogg")
add_sound("imperial", r"^imperial\W?$", "sound/funnysounds/imperial.ogg")
add_sound("im your father", r"^i'?m your father\W?$", "sound/funnysounds/imyourfather.ogg")
add_sound("indiana jones", r"^indiana jones\W?$", "sound/funnysounds/indianajones.ogg")
add_sound("in your head zombie", r"^in your head zombie\W?$", "sound/funnysounds/inyourheadzombie.ogg")
add_sound("i see dead people", r"^i see dead people\W?$", "sound/funnysounds/iseedeadpeople.ogg")
add_sound("its my life", r"^it'?s my life\W?$", "sound/funnysounds/itsmylife.ogg")
add_sound("its not", r"^it'?s not\W?$", "sound/funnysounds/itsnot.ogg")
add_sound("jesus", r"^jesus\W?$", "sound/funnysounds/jesus.ogg")
add_sound("johncena", r"^johncena\W?$", "sound/funnysounds/johncena.ogg")
add_sound("kamehameha", r"^kamehameha\W?$", "sound/funnysounds/kamehameha.ogg")
add_sound("keep your shirt on", r"^keep your shirt on\W?$", "sound/funnysounds/keepyourshirton.ogg")
add_sound("kommtdiesonne", r"^kommtdiesonne\W?$", "sound/funnysounds/kommtdiesonne.ogg")
add_sound("kungfu", r"^kungfu\W?$", "sound/funnysounds/kungfu.ogg")
add_sound("lately", r"^lately\W?$", "sound/funnysounds/lately.ogg")
add_sound("lets get ready", r"^lets get ready\W?$", "sound/funnysounds/letsgetready.ogg")
add_sound("lets put a smile", r"^lets put a smile\W?$", "sound/funnysounds/letsputasmile.ogg")
add_sound("lights out", r"^lights out\W?$", "sound/funnysounds/lightsout.ogg")
add_sound("live to win", r"^live to win\W?$", "sound/funnysounds/livetowin.ogg")
add_sound("loveme", r"^loveme\W?$", "sound/funnysounds/loveme.ogg")
add_sound("low", r"^low\W?$", "sound/funnysounds/low.ogg")
add_sound("luck", r"^luck\W?$", "sound/funnysounds/luck.ogg")
add_sound("lust", r"^lust\W?$", "sound/funnysounds/lust.ogg")
add_sound("meinland", r"^meinland\W?$", "sound/funnysounds/meinland.ogg")
add_sound("message", r"^message\W?$", "sound/funnysounds/message.ogg")
add_sound("mission", r"^mission\W?$", "sound/funnysounds/mission.ogg")
add_sound("mortal kombat", r"^mortal kombat\W?$", "sound/funnysounds/mortalkombat.ogg")
add_sound("move ass", r"^move ass\W?$", "sound/funnysounds/moveass.ogg")
add_sound("muppet opening", r"^muppet opening\W?$", "sound/funnysounds/muppetopening.ogg")
add_sound("my little pony", r"^my little pony\W?$", "sound/funnysounds/mylittlepony.ogg")
add_sound("never seen", r"^never seen\W?$", "sound/funnysounds/neverseen.ogg")
add_sound("nightmare", r"^nightmare\W?$", "sound/funnysounds/nightmare.ogg")
add_sound("nobody likes you", r"^nobody likes you\W?$", "sound/funnysounds/nobodylikesyou.ogg")
add_sound("nonie", r"^nonie\W?$", "sound/funnysounds/nonie.ogg")
add_sound("nooo", r"^nooo\W?$", "sound/funnysounds/nooo.ogg")
add_sound("numanuma", r"^numanuma\W?$", "sound/funnysounds/numanuma.ogg")
add_sound("nyancat", r"^nyancat\W?$", "sound/funnysounds/nyancat.ogg")
add_sound("o fuck", r"^o fuck\W?$", "sound/funnysounds/ofuck.ogg")
add_sound("oh my god", r"^oh my god\W?$", "sound/funnysounds/ohmygod.ogg")
add_sound("ohnedich", r"^ohnedich\W?$", "sound/funnysounds/ohnedich.ogg")
add_sound("oh no", r"^oh no\W?$", "sound/funnysounds/ohno.ogg")
add_sound("oh noe", r"^oh noe\W?$", "sound/funnysounds/ohnoe.ogg")
add_sound("pacman", r"^pacman\W?$", "sound/funnysounds/pacman.ogg")
add_sound("pick me up", r"^pick me up\W?$", "sound/funnysounds/pickmeup.ogg")
add_sound("pikachu", r"^pikachu\W?$", "sound/funnysounds/pikachu.ogg")
add_sound("pinkiepie", r"^pinkiepie\W?$", "sound/funnysounds/pinkiepie.ogg")
add_sound("pipe", r"^pipe\W?$", "sound/funnysounds/pipe.ogg")
add_sound("piss me off", r"^piss me off\W?$", "sound/funnysounds/pissmeoff.ogg")
add_sound("play a game", r"^play a game\W?$", "sound/funnysounds/playagame.ogg")
add_sound("pooping", r"^pooping\W?$", "sound/funnysounds/pooping.ogg")
add_sound("powerpuff", r"^powerpuff\W?$", "sound/funnysounds/powerpuff.ogg")
add_sound("radioactive", r"^radioactive\W?$", "sound/funnysounds/radioactive.ogg")
add_sound("rammsteinriff", r"^rammsteinriff\W?$", "sound/funnysounds/rammsteinriff.ogg")
add_sound("redwins", r"^redwins\W?$", "sound/funnysounds/redwins.ogg")
add_sound("renegade", r"^renegade\W?$", "sound/funnysounds/renegade.ogg")
add_sound("retard", r"^retard\W?$", "sound/funnysounds/retard.ogg")
add_sound("rockyouguitar", r"^rockyouguitar\W?$", "sound/funnysounds/rockyouguitar.ogg")
add_sound("sail", r"^sail\W?$", "sound/funnysounds/sail.ogg")
add_sound("sandstorm", r"^sandstorm\W?$", "sound/funnysounds/sandstorm.ogg")
add_sound("saymyname", r"^saymyname\W?$", "sound/funnysounds/saymyname.ogg")
add_sound("sellyouall", r"^sellyouall\W?$", "sound/funnysounds/sellyouall.ogg")
add_sound("senseofhumor", r"^senseofhumor\W?$", "sound/funnysounds/senseofhumor.ogg")
add_sound("shakesenora", r"^shakesenora\W?$", "sound/funnysounds/shakesenora.ogg")
add_sound("shut the fuckup", r"^shut the fuck up\W?$", "sound/funnysounds/shutthefuckup.ogg")
add_sound("shut your fucking mouth", r"^shut your fucking mouth\W?$", "sound/funnysounds/shutyourfuckingmouth.ogg")
add_sound("smooth criminal", r"^smooth criminal\W?$", "sound/funnysounds/smoothcriminal.ogg")
add_sound("socobatevira", r"^socobatevira\W?$", "sound/funnysounds/socobatevira.ogg")
add_sound("ssocobatevira end", r"^socobatevira end\W?$", "sound/funnysounds/socobateviraend.ogg")
add_sound("socobatevira fast", r"^socobatevira fast\W?$", "sound/funnysounds/socobatevirafast.ogg")
add_sound("socobatevira slow", r"^socobatevira slow\W?$", "sound/funnysounds/socobateviraslow.ogg")
add_sound("sogivemereason", r"^sogivemereason\W?$", "sound/funnysounds/sogivemereason.ogg")
add_sound("so stupid", r"^so stupid\W?$", "sound/funnysounds/sostupid.ogg")
add_sound("space unicorn", r"^space unicorn\W?$", "sound/funnysounds/spaceunicorn.ogg")
add_sound("spierdalaj", r"^spierdalaj\W?$", "sound/funnysounds/spierdalaj.ogg")
add_sound("stamp on", r"^stamp on\W?$", "sound/funnysounds/stampon.ogg")
add_sound("star wars", r"^star wars\W?$", "sound/funnysounds/starwars.ogg")
add_sound("stoning", r"^stoning\W?$", "sound/funnysounds/stoning.ogg")
add_sound("story", r"^story\W?$", "sound/funnysounds/story.ogg")
add_sound("swedish chef", r"^swedish chef\W?$", "sound/funnysounds/swedishchef.ogg")
add_sound("sweet dreams", r"^sweet dreams\W?$", "sound/funnysounds/sweetdreams.ogg")
add_sound("take me down", r"^take me down\W?$", "sound/funnysounds/takemedown.ogg")
add_sound("talk scotish", r"^talk scotish\W?$", "sound/funnysounds/talkscotish.ogg")
add_sound("technology", r"^technology\W?$", "sound/funnysounds/technology.ogg")
add_sound("thunderstruck", r"^thunderstruck\W?$", "sound/funnysounds/thunderstruck.ogg")
add_sound("to church", r"^to church\W?$", "sound/funnysounds/tochurch.ogg")
add_sound("tsunami", r"^tsunami\W?$", "sound/funnysounds/tsunami.ogg")
add_sound("unbelievable", r"^unbelievable\W?$", "sound/funnysounds/unbelievable.ogg")
add_sound("undderhaifisch", r"^undderhaifisch\W?$", "sound/funnysounds/undderhaifisch.ogg")
add_sound("up town girl", r"^up town girl\W?$", "sound/funnysounds/uptowngirl.ogg")
add_sound("valkyries", r"^valkyries\W?$", "sound/funnysounds/valkyries.ogg")
add_sound("wahwahwah", r"^wahwahwah\W?$", "sound/funnysounds/wahwahwah.ogg")
add_sound("want you", r"^want you\W?$", "sound/funnysounds/wantyou.ogg")
add_sound("wazzup", r"^wazzup\W?$", "sound/funnysounds/wazzup.ogg")
add_sound("wehmirohweh", r"^wehmirohweh\W?$", "sound/funnysounds/wehmirohweh.ogg")
add_sound("when angels", r"^when angels\W?$", "sound/funnysounds/whenangels.ogg")
add_sound("where are you", r"^where are you\W?$", "sound/funnysounds/whereareyou.ogg")
add_sound("whistle", r"^whistle\W?$", "sound/funnysounds/whistle.ogg")
add_sound("wimbaway", r"^wimbaway\W?$", "sound/funnysounds/wimbaway.ogg")
add_sound("windows", r"^windows\W?$", "sound/funnysounds/windows.ogg")
add_sound("would you like", r"^would you like\W?$", "sound/funnysounds/wouldyoulike.ogg")
add_sound("wtf", r"^wtf\W?$", "sound/funnysounds/wtf.ogg")
add_sound("yeee", r"^yeee\W?$", "sound/funnysounds/yeee.ogg")
add_sound("yesmaster", r"^yes master\W?$", "sound/funnysounds/yesmaster.ogg")
add_sound("holy shit", r"^holy shit\W?$", "sound/vo_female/holy_shit")
add_sound("impressive", r"^impressive\W?$", "sound/vo_female/impressive1.wav")
add_sound("excellent", r"^excellent\W?$", "sound/vo_evil/excellent1.wav")
add_sound("all skeet skeet", r"^all skeet skeet\W?$", "sound/funnysounds/allskeetskeet.ogg")
add_sound("bad boys", r"^bad boys\W?$", "sound/funnysounds/badboys.ogg")
add_sound("banana boat song", r"^banana boat song\W?$", "sound/funnysounds/bananaboatsong.ogg")
add_sound("come with me now", r"^come with me now\W?$", "sound/funnysounds/comewithmenow.ogg")
add_sound("danger zone", r"^danger zone\W?$", "sound/funnysounds/dangerzone.ogg")
add_sound("eat pussy", r"^eat pussy\W?$", "sound/funnysounds/eatpussy.ogg")
add_sound("eins zwei", r"^eins zwei\W?$", "sound/funnysounds/einszwei.ogg")
add_sound("feel good", r"^feel good\W?$", "sound/funnysounds/feelgood.ogg")
add_sound("jesus oh", r"^jesus oh\W?$", "sound/funnysounds/jesusoh.ogg")
add_sound("knocked down", r"^knocked down\W?$", "sound/funnysounds/knockeddown.ogg")
add_sound("legitness", r"^legitness\W?$", "sound/funnysounds/legitness.ogg")
add_sound("me", r"^me\W?$", "sound/funnysounds/me.ogg")
add_sound("oh my gosh", r"^oh my gosh\W?$", "sound/funnysounds/ohmygosh.ogg")
add_sound("pink panther", r"^pink panther\W?$", "sound/funnysounds/pinkpanther.ogg")
add_sound("salil", r"^salil\W?$", "sound/funnysounds/salil.ogg")
add_sound("space jam", r"^space jam\W?$", "sound/funnysounds/spacejam.ogg")
add_sound("stop", r"^stop\W?$", "sound/funnysounds/stop.ogg")
add_sound("will be singing", r"^will be singing\W?$", "sound/funnysounds/willbesinging.ogg")
add_sound("you", r"^you\W?$", "sound/funnysounds/you.ogg")

add_izi_sound("007", r"^007\W?$", "sound/izi_tunes/007.ogg")
add_izi_sound("10forstyle", r"^10forstyle\W?$", "sound/izi_sounds/10forstyle.ogg")
add_izi_sound("aaaaa", r"^aaaaa\W?$", "sound/izi_sounds/aaaaa.ogg")
add_izi_sound("aahoww", r"^aahoww\W?$", "sound/izi_sounds/aahoww.ogg")
add_izi_sound("aarrgghh", r"^aarrgghh\W?$", "sound/izi_sounds/scream.ogg")
add_izi_sound("abusive", r"^abusive\W?$", "sound/izi_sounds/abusive.ogg")
add_izi_sound("adams family", r"^adams family\W?$", "sound/izi_tunes/adamsfamily.ogg")
add_izi_sound("adamsfamily", r"^adamsfamily\W?$", "sound/izi_tunes/adamsfamily.ogg")
add_izi_sound("ahyes", r"^ahyes\W?$", "sound/izi_sounds/ahyes.ogg")
add_izi_sound("akbar", r"^akbar\W?$", "sound/izi_sounds/akbar.ogg")
add_izi_sound("allstar", r"^allstar\W?$", "sound/izi_tunes/allstar.ogg")
add_izi_sound("ameno", r"^ameno\W?$", "sound/izi_tunes/ameno.ogg")
add_izi_sound("analcream", r"^analcream\W?$", "sound/izi_sounds/analcream.ogg")
add_izi_sound("annoying", r"^annoying\W?$", "sound/izi_sounds/annoying.ogg")
add_izi_sound("areyouready", r"^areyouready\W?$", "sound/izi_sounds/areyouready.ogg")
add_izi_sound("assholes", r"^assholes\W?$", "sound/izi_sounds/assholes.ogg")
add_izi_sound("asskicking", r"^asskicking\W?$", "sound/izi_sounds/asskicking.ogg")
add_izi_sound("ave maria", r"^ave maria\W?$", "sound/izi_tunes/ave.ogg")
add_izi_sound("avemaria", r"^avemaria\W?$", "sound/izi_tunes/ave.ogg")
add_izi_sound("awesome", r"^awesome\W?$", "sound/izi_sounds/awesome.ogg")
add_izi_sound("babylaugh", r"^babylaugh\W?$", "sound/izi_sounds/baby.ogg")
add_izi_sound("backstabbing", r"^backstabbing\W?$", "sound/izi_sounds/backstabbing.ogg")
add_izi_sound("badass", r"^badass\W?$", "sound/izi_sounds/badass.ogg")
add_izi_sound("badfeeling", r"^badfeeling\W?$", "sound/izi_sounds/badfeeling.ogg")
add_izi_sound("bamba", r"^bamba\W?$", "sound/izi_sounds/bamba.ogg")
add_izi_sound("bananas", r"^bananas\W?$", "sound/izi_sounds/bananas.ogg")
add_izi_sound("bazooka", r"^bazooka\W?$", "sound/izi_sounds/bazooka.ogg")
add_izi_sound("bb", r"^bb\W?$", "sound/izi_sounds/bb.ogg")
add_izi_sound("bendover", r"^bendover\W?$", "sound/izi_sounds/bendover.ogg")
add_izi_sound("bennyhill", r"^bennyhill\W?$", "sound/izi_tunes/bennyhill.ogg")
add_izi_sound("bestyoucando", r"^bestyoucando\W?$", "sound/izi_sounds/bestyoucando.ogg")
add_izi_sound("blablabla", r"^blablabla\W?$", "sound/izi_sounds/blablabla.ogg")
add_izi_sound("bloodonmysuit", r"^bloodonmysuit\W?$", "sound/izi_sounds/bloodonmysuit.ogg")
add_izi_sound("blue wins", r"^blue wins\W?$", "sound/izi_tunes/bluewins.ogg")
add_izi_sound("bluewins", r"^bluewins\W?$", "sound/izi_tunes/bluewins.ogg")
add_izi_sound("bombhasbeenplanted", r"^bombhasbeenplanted\W?$", "sound/izi_sounds/bombhasbeenplanted.ogg")
add_izi_sound("bonkers", r"^bonkers\W?$", "sound/izi_tunes/bonkers.ogg")
add_izi_sound("boohoo", r"^boohoo\W?$", "sound/izi_sounds/boohoo.ogg")
add_izi_sound("boomheadshot", r"^boomheadshot\W?$", "sound/izi_sounds/boomheadshot.ogg")
add_izi_sound("british", r"^british\W?$", "sound/izi_countrys/british.ogg")
add_izi_sound("brutal", r"^brutal\W?$", "sound/izi_sounds/brutal.ogg")
add_izi_sound("bugme", r"^bugme\W?$", "sound/izi_sounds/bugme.ogg")
add_izi_sound("bullshit", r"^bullshit\W?$", "sound/izi_sounds/bullshit.ogg")
add_izi_sound("bullshitter", r"^bullshitter\W?$", "sound/izi_sounds/bullshitter.ogg")
add_izi_sound("cameltoe", r"^cameltoe\W?$", "sound/izi_sounds/cameltoe.ogg")
add_izi_sound("camper", r"^camper\W?$", "sound/izi_sounds/camper.ogg")
add_izi_sound("cant touch this", r"^cant touch this\W?$", "sound/izi_tunes/canttouchthis.ogg")
add_izi_sound("canttouchthis", r"^canttouchthis\W?$", "sound/izi_tunes/canttouchthis.ogg")
add_izi_sound("chacaron", r"^chacaron\W?$", "sound/izi_tunes/chacaron.ogg")
add_izi_sound("champions", r"^champions\W?$", "sound/izi_tunes/champions.ogg")
add_izi_sound("chickentune", r"^chickentune\W?$", "sound/izi_tunes/chicken.ogg")
add_izi_sound("choppa", r"^choppa\W?$", "sound/izi_sounds/choppa.ogg")
add_izi_sound("claxon", r"^claxon\W?$", "sound/izi_sounds/claxon.ogg")
add_izi_sound("classic", r"^classic\W?$", "sound\izi_music\izi_music31.ogg")
add_izi_sound("combobreaker", r"^combobreaker\W?$", "sound/izi_sounds/combobreaker.ogg")
add_izi_sound("come", r"^come\W?$", "sound/izi_sounds/come.ogg")
add_izi_sound("comehere", r"^comehere\W?$", "sound/izi_sounds/comehere.ogg")
add_izi_sound("countdown", r"^countdown\W?$", "sound/izi_sounds/countdown.ogg")
add_izi_sound("crap", r"^crap\W?$", "sound/izi_sounds/crap.ogg")
add_izi_sound("cunt", r"^cunt\W?$", "sound/izi_tunes/cunt.ogg")
add_izi_sound("cutiepie", r"^cutiepie\W?$", "sound/izi_sounds/cutiepie.ogg")
add_izi_sound("danish", r"^danish\W?$", "sound\izi_countrys\danish.ogg")
add_izi_sound("daddy", r"^daddy\W?$", "sound/izi_sounds/daddy.ogg")
add_izi_sound("damnyou", r"^damnyou\W?$", "sound/izi_sounds/damnyou.ogg")
add_izi_sound("deadsoon", r"^deadsoon\W?$", "sound/izi_sounds/deadsoon.ogg")
add_izi_sound("devil", r"^devil\W?$", "sound/izi_tunes/devil.ogg")
add_izi_sound("digthis", r"^digthis\W?$", "sound/izi_sounds/digthis.ogg")
add_izi_sound("dinohowl", r"^dinohowl\W?$", "sound/izi_sounds/dinohowl.ogg")
add_izi_sound("dominating", r"^dominating\W?$", "sound/izi_sounds/dominating.ogg")
add_izi_sound("donald duck", r"^donald duck\W?$", "sound/izi_sounds/donaldduck.ogg")
add_izi_sound("dontmake", r"^dontmake\W?$", "sound/izi_sounds/dontmake.ogg")
add_izi_sound("dontthinkso", r"^dontthinkso\W?$", "sound/izi_sounds/donthtinkso.ogg")
add_izi_sound("dropthebeat", r"^dropthebeat\W?$", "sound/izi_sounds/dropthebeat.ogg")
add_izi_sound("dutch", r"^dutch\W?$", "sound\izi_countrys\dutch1.ogg")
add_izi_sound("eatme", r"^eatme\W?$", "sound/izi_sounds/eatme.ogg")
add_izi_sound("education", r"^education\W?$", "sound/izi_tunes/education.ogg")
add_izi_sound("eight", r"^eight\W?$", "sound/izi_sounds/eight.ogg")
add_izi_sound("electro", r"^electro\W?$", "sound/izi_tunes/electro.ogg")
add_izi_sound("english", r"^english\W?$", "sound/izi_sounds/english.ogg")
add_izi_sound("explosions", r"^explosions\W?$", "sound/izi_sounds/explosions.ogg")
add_izi_sound("faceripoff", r"^faceripoff\W?$", "sound/izi_sounds/faceripoff.ogg")
add_izi_sound("fail", r"^fail\W?$", "sound/izi_sounds/fail.ogg")
add_izi_sound("fatality", r"^fatality\W?$", "sound/izi_sounds/fatality.ogg")
add_izi_sound("fatbastard", r"^fatbastard\W?$", "sound/izi_sounds/fatbastard.ogg")
add_izi_sound("fight", r"^fight\W?$", "sound/izi_sounds/fight.ogg")
add_izi_sound("fightme", r"^fightme\W?$", "sound/izi_sounds/fightme.ogg")
add_izi_sound("finishher", r"^finishher\W?$", "sound/izi_sounds/finishher.ogg")
add_izi_sound("finishhim", r"^finishhim\W?$", "sound/izi_sounds/finishhim.ogg")
add_izi_sound("firefight", r"^firefight\W?$", "sound/izi_sounds/firefight.ogg")
add_izi_sound("five", r"^five\W?$", "sound/izi_sounds/five.ogg")
add_izi_sound("flawlessvictory", r"^flawlessvictory\W?$", "sound/izi_sounds/flawlessvictory.ogg")
add_izi_sound("fool", r"^fool\W?$", "sound/izi_sounds/fool.ogg")
add_izi_sound("four", r"^four\W?$", "sound/izi_sounds/four.ogg")
add_izi_sound("freaks", r"^freaks\W?$", "sound/izi_sounds/freaks.ogg")
add_izi_sound("freestyler", r"^freestyler\W?$", "sound/izi_tunes/freestyler.ogg")
add_izi_sound("freshair", r"^freshair\W?$", "sound/izi_sounds/freshair.ogg")
add_izi_sound("fuck", r"^fuck\W?$", "sound/izi_sounds/fuck.ogg")
add_izi_sound("fuckout", r"^fuckout\W?$", "sound/izi_sounds/fuckout.ogg")
add_izi_sound("fuckyouall", r"^fuckyouall\W?$", "sound/izi_sounds/fuckyouall.ogg")
add_izi_sound("fuckyourface", r"^fuckyourface\W?$", "sound/izi_sounds/fuckyourface.ogg")
add_izi_sound("fuckyouup", r"^fuckyouup\W?$", "sound/izi_sounds/fuckyouup.ogg")
add_izi_sound("fun", r"^fun\W?$", "sound/izi_sounds/laugh6.ogg")
add_izi_sound("gameover", r"^gameover\W?$", "sound/izi_sounds/gameover.ogg")
add_izi_sound("gangbang", r"^gangbang\W?$", "sound/izi_sounds/gangbang.ogg")
add_izi_sound("gangnam", r"^gangnam\W?$", "sound/izi_tunes/gangnam.ogg")
add_izi_sound("ganjaman", r"^ganjaman\W?$", "sound/izi_tunes/ganjaman.ogg")
add_izi_sound("gargl", r"^gargl\W?$", "sound/izi_sounds/gargl.ogg")
add_izi_sound("gay", r"^gay\W?$", "sound/izi_sounds/gay.ogg")
add_izi_sound("geronimo", r"^geronimo\W?$", "sound/izi_sounds/geronimo.ogg")
add_izi_sound("get out the way", r"^get out the way\W?$", "sound/izi_tunes/getouttheway.ogg")
add_izi_sound("getoffscum", r"^getoffscum\W?$", "sound/izi_sounds/getoffscum.ogg")
add_izi_sound("getout", r"^getout\W?$", "sound/izi_sounds/getout.ogg")
add_izi_sound("getouttheway", r"^getouttheway\W?$", "sound/izi_tunes/getouttheway.ogg")
add_izi_sound("ghostbusters", r"^ghostbusters\W?$", "sound/izi_tunes/ghostbusters.ogg")
add_izi_sound("girly", r"^girly\W?$", "sound/izi_tunes/girly.ogg")
add_izi_sound("givemeorders", r"^givemeorders\W?$", "sound/izi_sounds/givemeorders.ogg")
add_izi_sound("goddamn", r"^goddamn\W?$", "sound/izi_sounds/goddammit.ogg")
add_izi_sound("gogogo", r"^gogogo\W?$", "sound/izi_sounds/gogogo.ogg")
add_izi_sound("gong", r"^gong\W?$", "sound/izi_sounds/gong.ogg")
add_izi_sound("good2go", r"^good2go\W?$", "sound/izi_sounds/good2go.ogg")
add_izi_sound("goodbye", r"^goodbye\W?$", "sound/izi_tunes/goodbyesarah.ogg")
add_izi_sound("goosebumps", r"^goosebumps\W?$", "sound/izi_sounds/goosebumps.ogg")
add_izi_sound("gotcha", r"^gotcha\W?$", "sound/izi_sounds/gotcha.ogg")
add_izi_sound("gottamove", r"^gottamove\W?$", "sound/izi_sounds/gottamove.ogg")
add_izi_sound("greatshot", r"^greatshot\W?$", "sound/izi_sounds/greatshot.ogg")
add_izi_sound("growl", r"^growl\W?$", "sound/izi_sounds/growl.ogg")
add_izi_sound("guarentee", r"^guarentee\W?$", "sound/izi_sounds/guarentee.ogg")
add_izi_sound("hairy", r"^hairy\W?$", "sound/izi_sounds/hairy.ogg")
add_izi_sound("hakuna", r"^hakuna\W?$", "sound/izi_sounds/hakunamatata.ogg")
add_izi_sound("headshot", r"^headshot\W?$", "sound/izi_sounds/headshot.ogg")
add_izi_sound("heavenly", r"^heavenly\W?$", "sound/izi_sounds/heavenly.ogg")
add_izi_sound("hehehe", r"^hehehe\W?$", "sound/izi_sounds/hehehe.ogg")
add_izi_sound("hellobabe", r"^hellobabe\W?$", "sound/izi_sounds/hellobabe.ogg")
add_izi_sound("heyyyy", r"^heyyyy\W?$", "sound/izi_sounds/heyyyy.ogg")
add_izi_sound("hindi", r"^hindi\W?$", "sound\izi_music\izi_music16.ogg")
add_izi_sound("holy", r"^holy\W?$", "sound/izi_sounds/holy.ogg")
add_izi_sound("holyshit", r"^holyshit\W?$", "sound/izi_sounds/holyshit.ogg")
add_izi_sound("horsie", r"^horsie\W?$", "sound/izi_sounds/horsie.ogg")
add_izi_sound("hothothot", r"^hothothot\W?$", "sound/izi_sounds/hothothot.ogg")
add_izi_sound("howl", r"^howl\W?$", "sound/izi_sounds/howl.ogg")
add_izi_sound("huhuha", r"^huhuha\W?$", "sound/izi_sounds/huhuha.ogg")
add_izi_sound("hukuna2", r"^hukuna2\W?$", "sound/izi_tunes/hakunamatata.ogg")
add_izi_sound("hungarian", r"^hungarian\W?$", "sound\izi_countrys\hungarian.ogg")
add_izi_sound("hurensohn", r"^hurensohn\W?$", "sound/izi_sounds/hurensohn.ogg")
add_izi_sound("hurtmyfeelings", r"^hurtmyfeelings\W?$", "sound/izi_sounds/hurtmyfeelings.ogg")
add_izi_sound("ibet", r"^ibet\W?$", "sound/izi_sounds/ibet.ogg")
add_izi_sound("idontthinkso", r"^idontthinkso\W?$", "sound/izi_sounds/idontthinkso.ogg")
add_izi_sound("ihateall", r"^ihateall\W?$", "sound/izi_sounds/ihateall.ogg")
add_izi_sound("ikilledyou", r"^ikilledyou\W?$", "sound/izi_sounds/ikilledyou.ogg")
add_izi_sound("iluvu2", r"^iluvu2\W?$", "sound/izi_sounds/iluvu2.ogg")
add_izi_sound("imgood", r"^imgood\W?$", "sound/izi_sounds/imgood.ogg")
add_izi_sound("imove4noman", r"^imove4noman\W?$", "sound/izi_sounds/imove4noman.ogg")
add_izi_sound("imperial", r"^imperial\W?$", "sound/izi_tunes/imperial.ogg")
add_izi_sound("imwaiting", r"^imwaiting\W?$", "sound/izi_sounds/imwaiting.ogg")
add_izi_sound("incoming", r"^incoming\W?$", "sound/izi_sounds/incoming.ogg")
add_izi_sound("indiana", r"^indiana\W?$", "sound/izi_tunes/indianajones.ogg")
add_izi_sound("ishedead", r"^ishedead\W?$", "sound/izi_sounds/ishedead.ogg")
add_izi_sound("itoldyou", r"^itoldyou\W?$", "sound/izi_sounds/itoldyouiwouldfindyou.ogg")
add_izi_sound("itson", r"^itson\W?$", "sound/izi_sounds/itson.ogg")
add_izi_sound("iwillkillyou", r"^iwillkillyou\W?$", "sound/izi_sounds/iwillkillyou.ogg")
add_izi_sound("izipizi", r"^izipizi\W?$", "sound/izi_sounds/izipizi.ogg")
add_izi_sound("jesus", r"^jesus\W?$", "sound/izi_sounds/jesus.ogg")
add_izi_sound("jodel", r"^jodel\W?$", "sound\izi_music\izi_music29.ogg")
add_izi_sound("justdie", r"^justdie\W?$", "sound/izi_sounds/justdie.ogg")
add_izi_sound("justdoit", r"^justdoit\W?$", "sound/izi_sounds/justdoit.ogg")
add_izi_sound("kaboom", r"^kaboom\W?$", "sound/izi_sounds/kaboom.ogg")
add_izi_sound("killer", r"^killer\W?$", "sound/izi_sounds/killer.ogg")
add_izi_sound("killingmachine", r"^killingmachine\W?$", "sound/izi_sounds/killingmachine.ogg")
add_izi_sound("killyourself", r"^killyourself\W?$", "sound/izi_sounds/killyourself.ogg")
add_izi_sound("kungfufighting", r"^kungfufighting\W?$", "sound/izi_tunes/kungfu.ogg")
add_izi_sound("letsgetready", r"^letsgetready\W?$", "sound/izi_sounds/letsgetready.ogg")
add_izi_sound("licklead", r"^licklead\W?$", "sound/izi_sounds/licklead.ogg")
add_izi_sound("lifesux", r"^lifesux\W?$", "sound/izi_sounds/lifesux.ogg")
add_izi_sound("lion", r"^lion\W?$", "sound/izi_sounds/lion.ogg")
add_izi_sound("lion king", r"^lion king\W?$", "sound/izi_tunes/lionking.ogg")
add_izi_sound("lionking", r"^lionking\W?$", "sound/izi_tunes/lionking.ogg")
add_izi_sound("lithuanian", r"^lithuanian\W?$", "sound\izi_countrys\lithuanian.ogg")
add_izi_sound("longforcombat", r"^longforcombat\W?$", "sound/izi_sounds/longforcombat.ogg")
add_izi_sound("lost", r"^lost\W?$", "sound/izi_sounds/lost.ogg")
add_izi_sound("loudnoises", r"^loudnoises\W?$", "sound/izi_sounds/loudnoises.ogg")
add_izi_sound("love", r"^love\W?$", "sound/izi_tunes/whatislove.ogg")
add_izi_sound("low", r"^low\W?$", "sound/izi_sounds/low.ogg")
add_izi_sound("lukang", r"^lukang\W?$", "sound/izi_sounds/lukang.ogg")
add_izi_sound("maersong", r"^maersong\W?$", "sound\izi_music\izi_music19.ogg")
add_izi_sound("mahna", r"^mahna\W?$", "sound/izi_tunes/mahnamahna.ogg")
add_izi_sound("mario", r"^mario\W?$", "sound/izi_sounds/mario.ogg")
add_izi_sound("master", r"^master\W?$", "sound/izi_sounds/master.ogg")
add_izi_sound("medic", r"^medic\W?$", "sound/izi_sounds/medic.ogg")
add_izi_sound("meepmeep", r"^meepmeep\W?$", "sound/izi_sounds/meepmeep.ogg")
add_izi_sound("mewins", r"^mewins\W?$", "sound/izi_sounds/mewins.ogg")
add_izi_sound("milkshake", r"^milkshake\W?$", "sound/izi_sounds/milkshake.ogg")
add_izi_sound("mimi", r"^mimi\W?$", "sound/izi_tunes/mimimi.ogg")
add_izi_sound("missiles", r"^missiles\W?$", "sound/izi_sounds/missiles.ogg")
add_izi_sound("missionimpossible", r"^missionimpossible\W?$", "sound/izi_tunes/mission.ogg")
add_izi_sound("monsterkill", r"^monsterkill\W?$", "sound/izi_sounds/monsterkill.ogg")
add_izi_sound("motherlessgoat", r"^motherlessgoat\W?$", "sound/izi_sounds/motherlessgoat.ogg")
add_izi_sound("mouahaha", r"^mouahaha\W?$", "sound/izi_sounds/mouahaha.ogg")
add_izi_sound("muppet", r"^muppet\W?$", "sound/izi_tunes/muppetopening.ogg")
add_izi_sound("nasty", r"^nasty\W?$", "sound/izi_sounds/nasty.ogg")
add_izi_sound("neverending", r"^neverending\W?$", "sound/izi_tunes/story.ogg")
add_izi_sound("neverlearn", r"^neverlearn\W?$", "sound/izi_sounds/neverlearn.ogg")
add_izi_sound("neverstop", r"^neverstop\W?$", "sound/izi_sounds/neverstopkillingyou.ogg")
add_izi_sound("nine", r"^nine\W?$", "sound/izi_sounds/nine.ogg")
add_izi_sound("nobody", r"^nobody\W?$", "sound/izi_tunes/nobodylikesyou.ogg")
add_izi_sound("norwegian", r"^norwegian\W?$", "sound/izi_countrys/norwegian.ogg")
add_izi_sound("noson", r"^noson\W?$", "sound/izi_sounds/noson.ogg")
add_izi_sound("nowisthetime", r"^nowisthetime\W?$", "sound/izi_sounds/nowisthetime.ogg")
add_izi_sound("numnut", r"^numnut\W?$", "sound/izi_sounds/numnut.ogg")
add_izi_sound("nyan", r"^nyan\W?$", "sound/izi_tunes/nyancat.ogg")
add_izi_sound("oeh", r"^oeh\W?$", "sound/izi_sounds/oeh.ogg")
add_izi_sound("ohno", r"^ohno\W?$", "sound/izi_sounds/ohno.ogg")
add_izi_sound("okletsgo", r"^okletsgo\W?$", "sound/izi_sounds/okletsgo.ogg")
add_izi_sound("overhere", r"^overhere\W?$", "sound/izi_sounds/overhere.ogg")
add_izi_sound("owned", r"^owned\W?$", "sound/izi_sounds/owned.ogg")
add_izi_sound("pacman", r"^pacman\W?$", "sound/izi_sounds/pacman.ogg")
add_izi_sound("pancakes", r"^pancakes\W?$", "sound/izi_sounds/pancakes.ogg")
add_izi_sound("pathetic", r"^pathetic\W?$", "sound/izi_sounds/pathetic.ogg")
add_izi_sound("paydenough", r"^paydenough\W?$", "sound/izi_sounds/paydenough.ogg")
add_izi_sound("pieceofme", r"^pieceofme\W?$", "sound/izi_sounds/pieceofme.ogg")
add_izi_sound("pinkpanther", r"^pinkpanther\W?$", "sound/izi_tunes/pinkpanther.ogg")
add_izi_sound("plasma", r"^plasma\W?$", "sound/izi_sounds/plasma.ogg")
add_izi_sound("playagame", r"^playagame\W?$", "sound/izi_sounds/playaGame.ogg")
add_izi_sound("polish", r"^polish\W?$", "sound\izi_countrys\polish.ogg")
add_izi_sound("prepare", r"^prepare\W?$", "sound/izi_sounds/prepare.ogg")
add_izi_sound("proud", r"^proud\W?$", "sound/izi_sounds/proud.ogg")
add_izi_sound("r2d2", r"^r2d2\W?$", "sound/izi_sounds/r2d2.ogg")
add_izi_sound("r2d2scream", r"^r2d2scream\W?$", "sound/izi_sounds/r2d2scream.ogg")
add_izi_sound("raaaah", r"^raaaah\W?$", "sound/izi_sounds/raaaah.ogg")
add_izi_sound("raaah", r"^raaah\W?$", "sound/izi_sounds/raaah.ogg")
add_izi_sound("ready", r"^ready\W?$", "sound/izi_sounds/ready.ogg")
add_izi_sound("red wins", r"^red wins\W?$", "sound/izi_tunes/redwins.ogg")
add_izi_sound("redwins", r"^redwins\W?$", "sound/izi_tunes/redwins.ogg")
add_izi_sound("resistance", r"^resistance\W?$", "sound/izi_sounds/resistance.ogg")
add_izi_sound("retard", r"^retard\W?$", "sound/izi_sounds/retard.ogg")
add_izi_sound("roar", r"^roar\W?$", "sound/izi_sounds/roar.ogg")
add_izi_sound("rooster", r"^rooster\W?$", "sound/izi_animals/rooster1.ogg")
add_izi_sound("run", r"^run\W?$", "sound/izi_sounds/runbitchrun.ogg")
add_izi_sound("runningback", r"^runningback\W?$", "sound/izi_sounds/runningback.ogg")
add_izi_sound("ruuuuh", r"^ruuuuh\W?$", "sound/izi_sounds/ruuuuh.ogg")
add_izi_sound("saidsmth", r"^saidsmth\W?$", "sound/izi_sounds/saidsmth.ogg")
add_izi_sound("sandstorm", r"^sandstorm\W?$", "sound/izi_tunes/sandstorm.ogg")
add_izi_sound("scatman", r"^scatman\W?$", "sound/izi_tunes/scatman.ogg")
add_izi_sound("scotish", r"^scotish\W?$", "sound/izi_tunes/talkscotish.ogg")
add_izi_sound("seeuinhell", r"^seeuinhell\W?$", "sound/izi_sounds/seeuinhell.ogg")
add_izi_sound("serioushurting", r"^serioushurting\W?$", "sound/izi_sounds/serioushurting.ogg")
add_izi_sound("seven", r"^seven\W?$", "sound/izi_sounds/seven.ogg")
add_izi_sound("sexy", r"^sexy\W?$", "sound/izi_tunes/imsexy.ogg")
add_izi_sound("shake", r"^shake\W?$", "sound/izi_tunes/shakesenora.ogg")
add_izi_sound("shiet", r"^shiet\W?$", "sound/izi_sounds/shieeeet.ogg")
add_izi_sound("shitonmyface", r"^shitonmyface\W?$", "sound/izi_sounds/shitonmyface.ogg")
add_izi_sound("shockwave", r"^shockwave\W?$", "sound/izi_sounds/shockwave.ogg")
add_izi_sound("shootthatfool", r"^shootthatfool\W?$", "sound/izi_sounds/shootthatfool.ogg")
add_izi_sound("shutup", r"^shutup\W?$", "sound/izi_sounds/shutup.ogg")
add_izi_sound("six", r"^six\W?$", "sound/izi_sounds/six.ogg")
add_izi_sound("skinflute", r"^skinflute\W?$", "sound/izi_sounds/skinflute.ogg")
add_izi_sound("sleepy", r"^sleepy\W?$", "sound/izi_tunes/sleepy.ogg")
add_izi_sound("smth2shoot", r"^smth2shoot\W?$", "sound/izi_sounds/smth2shoot.ogg")
add_izi_sound("snake", r"^snake\W?$", "sound/izi_sounds/snake.ogg")
add_izi_sound("sonofabitch", r"^sonofabitch\W?$", "sound/izi_sounds/sonofabitch.ogg")
add_izi_sound("spanish", r"^spanish\W?$", "sound\izi_music\izi_music32.ogg")
add_izi_sound("spell", r"^spell\W?$", "sound/izi_sounds/spell.ogg")
add_izi_sound("stamp", r"^stamp\W?$", "sound/izi_tunes/stampon.ogg")
add_izi_sound("starwars", r"^starwars\W?$", "sound/izi_tunes/starwars.ogg")
add_izi_sound("story", r"^story\W?$", "sound/izi_tunes/story.ogg")
add_izi_sound("suckyourself", r"^suckyourself\W?$", "sound/izi_sounds/suckyourself.ogg")
add_izi_sound("surprise", r"^surprise\W?$", "sound/izi_sounds/surprise.ogg")
add_izi_sound("suspence", r"^suspence\W?$", "sound/izi_sounds/suspence.ogg")
add_izi_sound("ssuuzsong", r"^ssuuzsong\W?$", "sound\izi_music\izi_music27.ogg")
add_izi_sound("takeit", r"^takeit\W?$", "sound/izi_sounds/takeit.ogg")
add_izi_sound("teamwork", r"^teamwork\W?$", "sound/izi_sounds/teamwork.ogg")
add_izi_sound("ten", r"^ten\W?$", "sound/izi_sounds/ten.ogg")
add_izi_sound("thatsright", r"^thatsright\W?$", "sound/izi_sounds/thatstight.ogg")
add_izi_sound("three", r"^three\W?$", "sound/izi_sounds/three.ogg")
add_izi_sound("toasty", r"^toasty\W?$", "sound/izi_sounds/feelthepoweroftoasty.ogg")
add_izi_sound("tooot", r"^tooot\W?$", "sound/izi_sounds/deeptoot.ogg")
add_izi_sound("tralala", r"^tralala\W?$", "sound/izi_sounds/tralala.ogg")
add_izi_sound("tsunami", r"^tsunami\W?$", "sound/izi_tunes/tsunami.ogg")
add_izi_sound("tunak", r"^tunak\W?$", "sound\izi_music\izi_music15.ogg")
add_izi_sound("tutu", r"^tutu\W?$", "sound/izi_tunes/tututu.ogg")
add_izi_sound("two", r"^two\W?$", "sound/izi_sounds/two.ogg")
add_izi_sound("typewriter", r"^typewriter\W?$", "sound/izi_tunes/typewriter.ogg")
add_izi_sound("ugly", r"^ugly\W?$", "sound/izi_sounds/uglymofo.ogg")
add_izi_sound("ultimate", r"^ultimate\W?$", "sound/izi_sounds/ultimate.ogg")
add_izi_sound("underwear", r"^underwear\W?$", "sound/izi_sounds/underwear.ogg")
add_izi_sound("unicorn", r"^unicorn\W?$", "sound/izi_tunes/spaceunicorn.ogg")
add_izi_sound("uuuh", r"^uuuh\W?$", "sound/izi_sounds/uuuh.ogg")
add_izi_sound("verywell", r"^verywell\W?$", "sound/izi_sounds/verywell.ogg")
add_izi_sound("victorious", r"^victorious\W?$", "sound/izi_sounds/win.ogg")
add_izi_sound("violentcontent", r"^violentcontent\W?$", "sound/izi_sounds/violentcontent.ogg")
add_izi_sound("wazzup", r"^wazzup\W?$", "sound/izi_sounds/wazzup.ogg")
add_izi_sound("wet", r"^wet\W?$", "sound/izi_sounds/wet.ogg")
add_izi_sound("wimbaway", r"^wimbaway\W?$", "sound/izi_tunes/wimbaway.ogg")
add_izi_sound("win", r"^win\W?$", "sound/izi_sounds/win.ogg")
add_izi_sound("windows", r"^windows\W?$", "sound/izi_sounds/windows.ogg")
add_izi_sound("winning", r"^winning\W?$", "sound/izi_sounds/winning.ogg")
add_izi_sound("wtf", r"^wtf\W?$", "sound/izi_sounds/wtf.ogg")
add_izi_sound("yehaw", r"^yehaw\W?$", "sound/izi_sounds/yehaw.ogg")
add_izi_sound("yesmaster", r"^yesmaster\W?$", "sound/izi_sounds/yesmaster.ogg")
add_izi_sound("yessir", r"^yessir\W?$", "sound/izi_sounds/yessir.ogg")
add_izi_sound("yourdaddy", r"^yourdaddy\W?$", "sound/izi_sounds/yourdaddy.ogg")
add_izi_sound("yourself", r"^yourself\W?$", "sound/izi_sounds/yourself.ogg")
add_izi_sound("yousuck", r"^yousuck\W?$", "sound/izi_sounds/yousuck.ogg")
add_izi_sound("youthinkimabitch", r"^youthinkimabitch\W?$", "sound/izi_sounds/youthinkimabitch.ogg")
add_izi_sound("youwantmore", r"^youwantmore\W?$", "sound/izi_sounds/youwantmore.ogg")
add_izi_sound("yummi", r"^yummi\W?$", "sound/izi_sounds/yummi.ogg")
add_izi_sound("zero", r"^zero\W?$", "sound/izi_sounds/zero.ogg")
add_izi_sound("zzz", r"^zzz\W?$", "sound/izi_tunes/sleepy.ogg")

add_izi_multi_sound(":(", r"^\:\(\W?$", "sound/izi_sounds/omg{}.ogg", 2)
add_izi_multi_sound(":o", r"^:o\W?$", "sound/izi_sounds/omg{}.ogg", 2)
add_izi_multi_sound(":|", r"^:\|\W?$", "sound/izi_sounds/omg{}.ogg", 2)
add_izi_multi_sound("babycry", r"^babycry\W?$", "sound/izi_sounds/babycry{}.ogg", 2)
add_izi_multi_sound("boing", r"^boing\W?$", "sound/izi_sounds/boing{}.ogg", 3)
add_izi_multi_sound("burp", r"^burp\W?$", "sound/izi_sounds/burp{}.ogg", 3)
add_izi_multi_sound("chicken", r"^chicken\W?$", "sound/izi_animals/chicken{}.ogg", 4)
add_izi_multi_sound("cow", r"^cow\W?$", "sound/izi_animals/cow{}.ogg", 7)
add_izi_multi_sound("dingeling", r"^dingeling\W?$", "sound/izi_sounds/dingeling{}.ogg", 3)
add_izi_multi_sound("dog", r"^dog\W?$", "sound/izi_animals/dog{}.ogg", 7)
add_izi_multi_sound("donkey", r"^donkey\W?$", "sound/izi_animals/donkey{}.ogg", 2)
add_izi_multi_sound("duck", r"^duck\W?$", "sound/izi_animals/duck{}.ogg", 4)
add_izi_multi_sound("dude", r"^dude\W?$", "sound/izi_sounds/dude{}.ogg", 2)
add_izi_multi_sound("fart", r"^fart\W?$", "sound/izi_sounds/fart{}.ogg", 8)
add_izi_multi_sound("goat", r"^goat\W?$", "sound/izi_animals/goat{}.ogg", 2)
add_izi_multi_sound("hahaha", r"^hahaha\W?$", "sound/izi_sounds/laugh{}.ogg", 6)
add_izi_multi_sound("horse", r"^horse\W?$", "sound/izi_animals/horse{}.ogg", 5)
add_izi_multi_sound("idiot", r"^idiot\W?$", "sound/izi_sounds/idiot{}.ogg", 6)
add_izi_multi_sound("issexy", r"^issexy\W?$", "sound/izi_sounds/issexy{}.ogg", 2)
add_izi_multi_sound("kungfu", r"^kungfu\W?$", "sound/izi_sounds/kungfu{}.ogg", 3)
add_izi_multi_sound("meow", r"^meow\W?$", "sound/izi_animals/cat{}.ogg", 3)
add_izi_multi_sound("music", r"^music\W?$", "sound\izi_music\izi_music{}.ogg", 74)
add_izi_multi_sound("omg", r"^omg\W?$", "sound/izi_sounds/omg{}.ogg", 2)
add_izi_multi_sound("orgasm", r"^orgasm\W?$", "sound/izi_sounds/orgasm{}.ogg", 6)
add_izi_multi_sound("outstanding", r"^outstanding\W?$", "sound/izi_sounds/outstanding{}.ogg", 2)
add_izi_multi_sound("punch", r"^punch\W?$", "sound/izi_sounds/punch{}.ogg", 4)
add_izi_multi_sound("sheep", r"^sheep\W?$", "sound/izi_animals/sheep{}.ogg", 4)
add_izi_multi_sound("slap", r"^slap\W?$", "sound/izi_sounds/slap{}.ogg", 9)
add_izi_multi_sound("squeek", r"^squeek\W?$", "sound/izi_sounds/squeek{}.ogg", 2)
add_izi_multi_sound("stfu", r"^stfu\W?$", "sound/izi_sounds/stfu{}.ogg", 2)
add_izi_multi_sound("welldone", r"^welldone\W?$", "sound/izi_sounds/welldone{}.ogg", 2)
add_izi_multi_sound("wickedsick", r"^wickedsick\W?$", "sound/izi_sounds/wickedsick{}.ogg", 2)


class funnysounds(minqlx.Plugin):
    database = Redis

    def __init__(self):
        super().__init__()
        self.add_hook("chat", self.handle_chat)
        self.add_command("cookies", self.cmd_cookies)
        self.last_sound = None
        self.add_command(("soundlist", "slist"), self.cmd_soundlist, client_cmd_perm=0, usage="<pagenum>")
        self.add_command(("izilist", "ilist"), self.cmd_izilist, client_cmd_perm=0, usage="<pagenum>")
        self.add_command(("izimultilist", "imlist"), self.cmd_izimultilist, client_cmd_perm=0, usage="<pagenum>")
        self.set_cvar_once("qlx_funSoundDelay", "3")

    def cmd_soundlist(self, player, msg, channel):
        """Prints a page of the sound list"""
        page = 0
        linesPerPage = 20
        totalpages = -(-len(_re_) // linesPerPage) -1  #ceil division trick to get pages for 10 items per page, -1 as 0= first.

        if len(msg) < 2:
            return minqlx.RET_USAGE

        if len(msg) > 1:
            try:
                page = int(msg[1])

            except ValueError:
                player.tell("Invalid page number.")
                return minqlx.RET_STOP_ALL

        page = page - 1
        if page > totalpages:
            page = totalpages
        if page < 1:
            page = 0
        player.tell("^5Sound list - page {} of {}".format(page + 1, totalpages + 1))
        for key in sorted(_re_)[page * linesPerPage:page * linesPerPage + linesPerPage]:  # slice for pagination
            player.tell("   ^2{}".format(key))

    def cmd_izilist(self, player, msg, channel):
        """Prints a page of the sound list"""
        page = 0
        linesPerPage = 20
        totalpages = -(-len(_izi_) // linesPerPage) -1  #ceil division trick to get pages for 10 items per page, -1 as 0= first.

        if len(msg) < 2:
            return minqlx.RET_USAGE

        if len(msg) > 1:
            try:
                page = int(msg[1])

            except ValueError:
                player.tell("Invalid page number.")
                return minqlx.RET_STOP_ALL

        page = page - 1
        if page > totalpages:
            page = totalpages
        if page < 1:
            page = 0
        player.tell("^5IZI sound list - page {} of {}".format(page + 1, totalpages + 1))
        for key in sorted(_izi_)[page * linesPerPage:page * linesPerPage + linesPerPage]:  # slice for pagination
            player.tell("   ^2{}".format(key))

    def cmd_izimultilist(self, player, msg, channel):
        """Prints a page of the sound list"""
        page = 0
        linesPerPage = 20
        totalpages = -(-len(_izi_multi_) // linesPerPage) -1  #ceil division trick to get pages for 10 items per page, -1 as 0= first.

        if len(msg) < 2:
            return minqlx.RET_USAGE

        if len(msg) > 1:
            try:
                page = int(msg[1])

            except ValueError:
                player.tell("Invalid page number.")
                return minqlx.RET_STOP_ALL

        page = page - 1
        if page > totalpages:
            page = totalpages
        if page < 1:
            page = 0
        player.tell("^5IZI multt sound list - page {} of {}".format(page + 1, totalpages + 1))
        for key in sorted(_izi_multi_)[page * linesPerPage:page * linesPerPage + linesPerPage]:  # slice for pagination
            player.tell("   ^2{}".format(key))

    def handle_chat(self, player, msg, channel):
        if channel != "chat":
            return

        msg = self.clean_text(msg)
        for key in _re_:
            if _re_[key][0].match(msg):
                self.play_sound(_re_[key][1])

        for key in _izi_:
            if _izi_[key][0].match(msg):
                self.play_sound(_izi_[key][1])

        for key in _izi_multi_:
            if _izi_multi_[key][0].match(msg):
                song = _izi_multi_[key][1]
                self.play_sound(song.format(random.randint(1, _izi_multi_[key][2])))

    def play_sound(self, path):
        if not self.last_sound:
            pass
        elif time.time() - self.last_sound < self.get_cvar("qlx_funSoundDelay", int):
            return

        self.last_sound = time.time()
        for p in self.players():
            if self.db.get_flag(p, "essentials:sounds_enabled", default=True):
                super().play_sound(path, p)

    def cmd_cookies(self, player, msg, channel):
        x = random.randint(0, 100)
        if not x:
            channel.reply("^6? ^7Here you go, {}. I baked these just for you! ^6?".format(player))
        elif x == 1:
            channel.reply("What, you thought ^6you^7 would get cookies from me, {}? Hah, think again.".format(player))
        elif x < 50:
            channel.reply("For me? Thank you, {}!".format(player))
        else:
            channel.reply("I'm out of cookies right now, {}. Sorry!".format(player))
